name: SOthisisthegridatlast
favicon: null
layout_spectrum: 0.6714785997755826
typography_spectrum: 0.8338265724014491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.896740963216871
  lightness: 0.24452822376042604
  saturation: 0.9800855373032391
  rhythmicContrast: 0.7658135637175292
purpose: []
